# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Auto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(393, 284)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_transmission = QtWidgets.QLabel(Dialog)
        self.label_transmission.setGeometry(QtCore.QRect(150, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_transmission.setFont(font)
        self.label_transmission.setObjectName("label_transmission")
        self.label_nbr_places = QtWidgets.QLabel(Dialog)
        self.label_nbr_places.setGeometry(QtCore.QRect(130, 110, 131, 16))
        self.label_nbr_places.setObjectName("label_nbr_places")
        self.label_type_carroserie = QtWidgets.QLabel(Dialog)
        self.label_type_carroserie.setGeometry(QtCore.QRect(130, 180, 131, 21))
        self.label_type_carroserie.setObjectName("label_type_carroserie")
        self.comboBox_transmission = QtWidgets.QComboBox(Dialog)
        self.comboBox_transmission.setGeometry(QtCore.QRect(130, 70, 121, 22))
        self.comboBox_transmission.setObjectName("comboBox_transmission")
        self.comboBox_transmission.addItem("")
        self.comboBox_transmission.addItem("")
        self.comboBox_transmission.addItem("")
        self.lineEdit_nbr_places = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nbr_places.setGeometry(QtCore.QRect(130, 130, 131, 20))
        self.lineEdit_nbr_places.setObjectName("lineEdit_nbr_places")
        self.comboBox_type_carosserie = QtWidgets.QComboBox(Dialog)
        self.comboBox_type_carosserie.setGeometry(QtCore.QRect(130, 200, 131, 22))
        self.comboBox_type_carosserie.setObjectName("comboBox_type_carosserie")
        self.comboBox_type_carosserie.addItem("")
        self.comboBox_type_carosserie.addItem("")
        self.label_error_nbr_places = QtWidgets.QLabel(Dialog)
        self.label_error_nbr_places.setGeometry(QtCore.QRect(130, 150, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_nbr_places.setFont(font)
        self.label_error_nbr_places.setObjectName("label_error_nbr_places")
        self.pushButton_ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(310, 250, 75, 31))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Auto"))
        self.label_transmission.setText(_translate("Dialog", "Trasmission"))
        self.label_nbr_places.setText(_translate("Dialog", "Nombre de places "))
        self.label_type_carroserie.setText(_translate("Dialog", "Type de carroserie"))
        self.comboBox_transmission.setItemText(0, _translate("Dialog", "Manuel "))
        self.comboBox_transmission.setItemText(1, _translate("Dialog", "Automatique "))
        self.comboBox_transmission.setItemText(2, _translate("Dialog", "Automatique/séquentielle"))
        self.comboBox_type_carosserie.setItemText(0, _translate("Dialog", "Sedan "))
        self.comboBox_type_carosserie.setItemText(1, _translate("Dialog", "Hatchback "))
        self.label_error_nbr_places.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">contenir 1 chiffres maximum</span></p></body></html>"))
        self.pushButton_ajouter.setText(_translate("Dialog", "Ajouter"))
