# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Camion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_nbr_portes = QtWidgets.QLabel(Dialog)
        self.label_nbr_portes.setGeometry(QtCore.QRect(120, 40, 131, 21))
        self.label_nbr_portes.setObjectName("label_nbr_portes")
        self.comboBox_nbr_portes = QtWidgets.QComboBox(Dialog)
        self.comboBox_nbr_portes.setGeometry(QtCore.QRect(120, 70, 131, 31))
        self.comboBox_nbr_portes.setObjectName("comboBox_nbr_portes")
        self.comboBox_nbr_portes.addItem("")
        self.comboBox_nbr_portes.addItem("")
        self.label_longueur_box = QtWidgets.QLabel(Dialog)
        self.label_longueur_box.setGeometry(QtCore.QRect(120, 120, 141, 21))
        self.label_longueur_box.setObjectName("label_longueur_box")
        self.lineEdit_longueur_box = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_longueur_box.setGeometry(QtCore.QRect(120, 140, 131, 20))
        self.lineEdit_longueur_box.setObjectName("lineEdit_longueur_box")
        self.label_error_longueur_box = QtWidgets.QLabel(Dialog)
        self.label_error_longueur_box.setGeometry(QtCore.QRect(120, 170, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_longueur_box.setFont(font)
        self.label_error_longueur_box.setObjectName("label_error_longueur_box")
        self.pushButton_ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(290, 260, 75, 31))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Camion"))
        self.label_nbr_portes.setText(_translate("Dialog", "Nombre de portes "))
        self.comboBox_nbr_portes.setItemText(0, _translate("Dialog", "2 portes"))
        self.comboBox_nbr_portes.setItemText(1, _translate("Dialog", "4 portes"))
        self.label_longueur_box.setText(_translate("Dialog", "Longueur de boite"))
        self.label_error_longueur_box.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">contenir que des chiffres positifs</span></p></body></html>"))
        self.pushButton_ajouter.setText(_translate("Dialog", "Ajouter"))
