# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 0, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_code_client = QtWidgets.QLabel(Dialog)
        self.label_code_client.setGeometry(QtCore.QRect(30, 60, 91, 21))
        self.label_code_client.setObjectName("label_code_client")
        self.label_nom_client = QtWidgets.QLabel(Dialog)
        self.label_nom_client.setGeometry(QtCore.QRect(240, 60, 91, 21))
        self.label_nom_client.setObjectName("label_nom_client")
        self.label_prenom_client = QtWidgets.QLabel(Dialog)
        self.label_prenom_client.setGeometry(QtCore.QRect(140, 120, 111, 31))
        self.label_prenom_client.setObjectName("label_prenom_client")
        self.lineEdit_code_client = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_code_client.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.lineEdit_code_client.setObjectName("lineEdit_code_client")
        self.lineEdit_nom_client = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nom_client.setGeometry(QtCore.QRect(220, 80, 113, 20))
        self.lineEdit_nom_client.setObjectName("lineEdit_nom_client")
        self.lineEdit_prenom_client = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_prenom_client.setGeometry(QtCore.QRect(130, 150, 113, 20))
        self.lineEdit_prenom_client.setObjectName("lineEdit_prenom_client")
        self.label_error_code_client = QtWidgets.QLabel(Dialog)
        self.label_error_code_client.setGeometry(QtCore.QRect(10, 100, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_code_client.setFont(font)
        self.label_error_code_client.setObjectName("label_error_code_client")
        self.label_error_longueur_nom = QtWidgets.QLabel(Dialog)
        self.label_error_longueur_nom.setGeometry(QtCore.QRect(190, 110, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_longueur_nom.setFont(font)
        self.label_error_longueur_nom.setObjectName("label_error_longueur_nom")
        self.label_error_prenom_client = QtWidgets.QLabel(Dialog)
        self.label_error_prenom_client.setGeometry(QtCore.QRect(210, 100, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_prenom_client.setFont(font)
        self.label_error_prenom_client.setObjectName("label_error_prenom_client")
        self.label_error_prenom_client_2 = QtWidgets.QLabel(Dialog)
        self.label_error_prenom_client_2.setGeometry(QtCore.QRect(120, 170, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_prenom_client_2.setFont(font)
        self.label_error_prenom_client_2.setObjectName("label_error_prenom_client_2")
        self.label_error_longueur_prenom = QtWidgets.QLabel(Dialog)
        self.label_error_longueur_prenom.setGeometry(QtCore.QRect(100, 180, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_longueur_prenom.setFont(font)
        self.label_error_longueur_prenom.setObjectName("label_error_longueur_prenom")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Client"))
        self.label_code_client.setText(_translate("Dialog", "Code Client"))
        self.label_nom_client.setText(_translate("Dialog", "Nom client"))
        self.label_prenom_client.setText(_translate("Dialog", "Prénom client"))
        self.label_error_code_client.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">contenir que 6 chiffres positifs</span></p><p><br/></p></body></html>"))
        self.label_error_longueur_nom.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir 50 caractères maximum</span></p></body></html>"))
        self.label_error_prenom_client.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir que des lettres</span></p><p><br/></p></body></html>"))
        self.label_error_prenom_client_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir que des lettres</span></p><p><br/></p></body></html>"))
        self.label_error_longueur_prenom.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir 50 caractères maximum</span></p></body></html>"))
