# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Contract_vente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_client = QtWidgets.QPushButton(Dialog)
        self.pushButton_client.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.pushButton_client.setObjectName("pushButton_client")
        self.pushButton_vendeur = QtWidgets.QPushButton(Dialog)
        self.pushButton_vendeur.setGeometry(QtCore.QRect(230, 210, 75, 23))
        self.pushButton_vendeur.setObjectName("pushButton_vendeur")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 260, 75, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_code_vente = QtWidgets.QLabel(Dialog)
        self.label_code_vente.setGeometry(QtCore.QRect(30, 40, 111, 16))
        self.label_code_vente.setObjectName("label_code_vente")
        self.label_prix_vente = QtWidgets.QLabel(Dialog)
        self.label_prix_vente.setGeometry(QtCore.QRect(200, 40, 121, 16))
        self.label_prix_vente.setObjectName("label_prix_vente")
        self.label_financement = QtWidgets.QLabel(Dialog)
        self.label_financement.setGeometry(QtCore.QRect(130, 110, 111, 16))
        self.label_financement.setObjectName("label_financement")
        self.comboBox_financement = QtWidgets.QComboBox(Dialog)
        self.comboBox_financement.setGeometry(QtCore.QRect(130, 130, 91, 22))
        self.comboBox_financement.setObjectName("comboBox_financement")
        self.comboBox_financement.addItem("")
        self.comboBox_financement.addItem("")
        self.comboBox_financement.addItem("")
        self.lineEdit_code_vente = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_code_vente.setGeometry(QtCore.QRect(30, 60, 113, 20))
        self.lineEdit_code_vente.setObjectName("lineEdit_code_vente")
        self.lineEdit_prix_vente = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_prix_vente.setGeometry(QtCore.QRect(200, 60, 113, 20))
        self.lineEdit_prix_vente.setObjectName("lineEdit_prix_vente")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(200, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Contract de vente"))
        self.pushButton_client.setText(_translate("Dialog", "Client"))
        self.pushButton_vendeur.setText(_translate("Dialog", "Vendeur"))
        self.pushButton_3.setText(_translate("Dialog", "Ajouter"))
        self.label_code_vente.setText(_translate("Dialog", "code de vente"))
        self.label_prix_vente.setText(_translate("Dialog", "Prix de la vente "))
        self.label_financement.setText(_translate("Dialog", "Financement"))
        self.comboBox_financement.setItemText(0, _translate("Dialog", "72 mois "))
        self.comboBox_financement.setItemText(1, _translate("Dialog", "40 mois "))
        self.comboBox_financement.setItemText(2, _translate("Dialog", "60 mois"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Contenir 6 chiffres positifs</span></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Contenir que des chiffres positifs</span></p><p><br/></p></body></html>"))
