# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_vehicule.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(140, 60, 131, 31))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")
        self.pushButton_modifier = QtWidgets.QPushButton(Dialog)
        self.pushButton_modifier.setGeometry(QtCore.QRect(140, 100, 131, 31))
        self.pushButton_modifier.setObjectName("pushButton_modifier")
        self.pushButton_suprimer = QtWidgets.QPushButton(Dialog)
        self.pushButton_suprimer.setGeometry(QtCore.QRect(140, 140, 131, 31))
        self.pushButton_suprimer.setObjectName("pushButton_suprimer")
        self.pushButton_afficher = QtWidgets.QPushButton(Dialog)
        self.pushButton_afficher.setGeometry(QtCore.QRect(140, 180, 131, 31))
        self.pushButton_afficher.setObjectName("pushButton_afficher")
        self.pushButton_quitter = QtWidgets.QPushButton(Dialog)
        self.pushButton_quitter.setGeometry(QtCore.QRect(320, 260, 71, 31))
        self.pushButton_quitter.setObjectName("pushButton_quitter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Main véhicule"))
        self.pushButton_ajouter.setText(_translate("Dialog", "Ajouter"))
        self.pushButton_modifier.setText(_translate("Dialog", "Modifier"))
        self.pushButton_suprimer.setText(_translate("Dialog", "Supprimer"))
        self.pushButton_afficher.setText(_translate("Dialog", "Afficher véhicule"))
        self.pushButton_quitter.setText(_translate("Dialog", "Quitter"))
