# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 353)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ajouter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(120, 50, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter.setFont(font)
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")
        self.pushButton_modifier = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_modifier.setGeometry(QtCore.QRect(120, 100, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_modifier.setFont(font)
        self.pushButton_modifier.setObjectName("pushButton_modifier")
        self.pushButton_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quitter.setGeometry(QtCore.QRect(120, 250, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_quitter.setFont(font)
        self.pushButton_quitter.setObjectName("pushButton_quitter")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 150, 231, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 200, 231, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Concessionnaire JDM cars"))
        self.pushButton_ajouter.setText(_translate("MainWindow", "Véhicule"))
        self.pushButton_modifier.setText(_translate("MainWindow", "Client"))
        self.pushButton_quitter.setText(_translate("MainWindow", "Quitter"))
        self.pushButton.setText(_translate("MainWindow", "Vendeur"))
        self.pushButton_2.setText(_translate("MainWindow", "Contract de vente"))
