# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vendeur.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_code_vendeur = QtWidgets.QLabel(Dialog)
        self.label_code_vendeur.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label_code_vendeur.setObjectName("label_code_vendeur")
        self.label_prenom = QtWidgets.QLabel(Dialog)
        self.label_prenom.setGeometry(QtCore.QRect(230, 52, 151, 21))
        self.label_prenom.setObjectName("label_prenom")
        self.label_nom_vendeur = QtWidgets.QLabel(Dialog)
        self.label_nom_vendeur.setGeometry(QtCore.QRect(130, 130, 121, 16))
        self.label_nom_vendeur.setObjectName("label_nom_vendeur")
        self.lineEdit_nom_vendeur = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nom_vendeur.setGeometry(QtCore.QRect(130, 150, 121, 20))
        self.lineEdit_nom_vendeur.setObjectName("lineEdit_nom_vendeur")
        self.lineEdit_code_vendeur = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_code_vendeur.setGeometry(QtCore.QRect(30, 70, 121, 20))
        self.lineEdit_code_vendeur.setObjectName("lineEdit_code_vendeur")
        self.lineEdit_prenom_vendeur = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_prenom_vendeur.setGeometry(QtCore.QRect(230, 70, 121, 20))
        self.lineEdit_prenom_vendeur.setObjectName("lineEdit_prenom_vendeur")
        self.pushButton_ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(320, 260, 75, 31))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")
        self.label_error_nom_vendeur = QtWidgets.QLabel(Dialog)
        self.label_error_nom_vendeur.setGeometry(QtCore.QRect(130, 170, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_nom_vendeur.setFont(font)
        self.label_error_nom_vendeur.setObjectName("label_error_nom_vendeur")
        self.label_error_prenom_vendeur = QtWidgets.QLabel(Dialog)
        self.label_error_prenom_vendeur.setGeometry(QtCore.QRect(230, 90, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_prenom_vendeur.setFont(font)
        self.label_error_prenom_vendeur.setObjectName("label_error_prenom_vendeur")
        self.label_error_code_vendeur = QtWidgets.QLabel(Dialog)
        self.label_error_code_vendeur.setGeometry(QtCore.QRect(10, 90, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_code_vendeur.setFont(font)
        self.label_error_code_vendeur.setObjectName("label_error_code_vendeur")
        self.label_error_longueur_nom = QtWidgets.QLabel(Dialog)
        self.label_error_longueur_nom.setGeometry(QtCore.QRect(100, 180, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_longueur_nom.setFont(font)
        self.label_error_longueur_nom.setObjectName("label_error_longueur_nom")
        self.label_error_longueur_prenom = QtWidgets.QLabel(Dialog)
        self.label_error_longueur_prenom.setGeometry(QtCore.QRect(200, 100, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_error_longueur_prenom.setFont(font)
        self.label_error_longueur_prenom.setObjectName("label_error_longueur_prenom")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Vendeur"))
        self.label_code_vendeur.setText(_translate("Dialog", "Code vendeur"))
        self.label_prenom.setText(_translate("Dialog", "Prénom du vendeur"))
        self.label_nom_vendeur.setText(_translate("Dialog", "Nom du vendeur "))
        self.pushButton_ajouter.setText(_translate("Dialog", "Ajouter"))
        self.label_error_nom_vendeur.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir que des lettres</span></p><p><br/></p></body></html>"))
        self.label_error_prenom_vendeur.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir que des lettres</span></p><p><br/></p></body></html>"))
        self.label_error_code_vendeur.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">contenir que 6 chiffres positifs</span></p><p><br/></p></body></html>"))
        self.label_error_longueur_nom.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir 50 caractères maximum</span></p></body></html>"))
        self.label_error_longueur_prenom.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff1202;\">Doit contenir 50 caractères maximum</span></p></body></html>"))
