# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ajouter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 264)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 0, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_vehicule = QtWidgets.QPushButton(Dialog)
        self.pushButton_vehicule.setGeometry(QtCore.QRect(160, 60, 161, 41))
        self.pushButton_vehicule.setObjectName("pushButton_vehicule")
        self.pushButton_contract_vente = QtWidgets.QPushButton(Dialog)
        self.pushButton_contract_vente.setGeometry(QtCore.QRect(160, 130, 161, 41))
        self.pushButton_contract_vente.setObjectName("pushButton_contract_vente")
        self.pushButton_quitter = QtWidgets.QPushButton(Dialog)
        self.pushButton_quitter.setGeometry(QtCore.QRect(160, 200, 161, 41))
        self.pushButton_quitter.setObjectName("pushButton_quitter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Ajouter"))
        self.pushButton_vehicule.setText(_translate("Dialog", "1- Ajouter véhicule"))
        self.pushButton_contract_vente.setText(_translate("Dialog", "2- Créer contract de vente "))
        self.pushButton_quitter.setText(_translate("Dialog", "Quitter "))
